In [2]:
import numpy as np
import math

In [3]:
data = np.array([[0.40,0.53],[0.22,0.38],[0.35,0.32],[0.26,0.19],[0.08,0.41],[0.48,0.30]])

In [4]:
print(data)
print(data.shape)

[[0.4  0.53]
 [0.22 0.38]
 [0.35 0.32]
 [0.26 0.19]
 [0.08 0.41]
 [0.48 0.3 ]]
(6, 2)


In [5]:
def getDistance(o1, o2):
#     print(f'Getting distance between {a},{b}')
    x2mx1sq = (o2[0]-o1[0])**2
    y2my1sq = (o2[1]-o1[1])**2
    return round(math.sqrt(x2mx1sq+y2my1sq), 2)

def getMinimium(distance_matrix):
    p = [0,0]
    mn = distance_matrix[0][0]
    for i in range(0, len(distance_matrix)):
        for j in range(0, len(distance_matrix[i])):
            if (distance_matrix[i][j]>0 and distance_matrix[i][j]<mn):
                mn = distance_matrix[i][j]
                p=[i,j]     
    return p

In [6]:
def createDistanceMatrix(array):
    distance_matrix = [[None for _ in range(array.shape[0])] for _ in range(array.shape[0])]
    for i in range(array.shape[0]):
            for j in range(0,i+1):
                distance_matrix[i][j] = getDistance(array[i,:], array[j,:])
    return np.array(distance_matrix)

In [72]:
def AgglomerativeClusteringScratch(array):
    
    distance_matrix = [[None for _ in range(array.shape[1])] for _ in range(array.shape[1])]
    clusters = list()
    distance_matrix = createDistanceMatrix(array)

    
    while(len(distance_matrix) > 2):
        new_distance_matrix = distance_matrix.copy()
        
        ## STEP 1: Find Mimimun:
        print(distance_matrix)
        minIndex = [1,0]
        minValue = distance_matrix[minIndex[0]][minIndex[1]]

        for i in range(len(distance_matrix)):
            for j in range(len(distance_matrix)):
                if(distance_matrix[i][j]):
                    if minValue > distance_matrix[i][j]:
                        minValue = distance_matrix[i][j]
                        minIndex = [i,j]

        print(f'\nMinimum: {minValue} at Index {minIndex}')
        newCluster = minIndex.copy()
        print(f'New Cluster: {newCluster}')
        
        clusters.append(newCluster)
        
        new_distance_matrix = np.delete(new_distance_matrix,minIndex[0],0)
        new_distance_matrix = np.delete(new_distance_matrix,minIndex[1],0)
        
        new_distance_matrix = np.delete(new_distance_matrix,minIndex[0],1)
        new_distance_matrix = np.delete(new_distance_matrix,minIndex[1],1)
        
        x= list()
        for n in range(len(new_distance_matrix)):
            if ~(n in minIndex):
                if (distance_matrix[minIndex[0]][n]):
                    a = distance_matrix[minIndex[0]][n]
                if (distance_matrix[minIndex[1]][n]):
                    b = distance_matrix[minIndex[1]][n]
                x.append(min(a,b))
        x.append(0.0)

        y = np.array(list([None] for _ in range(len(new_distance_matrix))))

        x = np.array([x])
        
        print('y:', y)
        print('x:', x)
        
        new_distance_matrix = np.hstack((new_distance_matrix, y))
        new_distance_matrix = np.vstack((new_distance_matrix, x))
        
        
        distance_matrix = new_distance_matrix.copy()
#         distance_matrix = np.delete(distance_matrix,minIndex[0],0)
#         distance_matrix = np.delete(distance_matrix,minIndex[1],0)
    return clusters
        
        
    
clusters_scratch = AgglomerativeClusteringScratch(data)
print('Clusters formed (in order): ', clusters_scratch)

[[0.0 None None None None None]
 [0.23 0.0 None None None None]
 [0.22 0.14 0.0 None None None]
 [0.37 0.19 0.16 0.0 None None]
 [0.34 0.14 0.28 0.28 0.0 None]
 [0.24 0.27 0.13 0.25 0.41 0.0]]

Minimum: 0.13 at Index [5, 2]
New Cluster: [5, 2]
y: [[None]
 [None]
 [None]
 [None]]
x: [[0.22 0.14 0.13 0.14 0.  ]]
[[0.0 None None None None]
 [0.23 0.0 None None None]
 [0.37 0.19 0.0 None None]
 [0.34 0.14 0.28 0.0 None]
 [0.22 0.14 0.13 0.14 0.0]]

Minimum: 0.13 at Index [4, 2]
New Cluster: [4, 2]
y: [[None]
 [None]
 [None]]
x: [[0.22 0.14 0.13 0.  ]]
[[0.0 None None None]
 [0.23 0.0 None None]
 [0.34 0.14 0.0 None]
 [0.22 0.14 0.13 0.0]]

Minimum: 0.13 at Index [3, 2]
New Cluster: [3, 2]
y: [[None]
 [None]]
x: [[0.22 0.14 0.  ]]
[[0.0 None None]
 [0.23 0.0 None]
 [0.22 0.14 0.0]]

Minimum: 0.14 at Index [2, 1]
New Cluster: [2, 1]
y: [[None]]
x: [[0.22 0.  ]]


In [44]:
a = [1,2,4]
b = 2
if ~(b in a):
    print('Bitch')

Bitch
